version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev libpng-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "app/composer.lock" }}
            - composer-v1-
      - run:
          command: composer install -n --prefer-dist --ignore-platform-reqs
          working_directory: ./app
      - save_cache:
          key: composer-v1-{{ checksum "app/composer.lock" }}
          paths:
            - app/vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "app/package.json" }}
            - node-v1-
      - run:
          command: yarn install
          working_directory: ./app
      - save_cache:
          key: node-v1-{{ checksum "app/package.json" }}
          paths:
            - app/node_modules
      - run: touch app/storage/testing.sqlite
      - run:
          command: php artisan migrate:fresh --env=testing --database=sqlite_testing --force
          working_directory: ./app
      - run:
          command: ./vendor/phpunit/phpunit/phpunit
          working_directory: ./app
      - run:
          command: yarn run production
          working_directory: ./app
      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true
          working_directory: ./app
      - run:
          command: cp .laravel.env.dusk.example ./app/.env
      - run:
          name: Run Laravel Server
          command: php artisan serve --port=21000
          background: true
          working_directory: ./app
      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
          working_directory: ./app